from selenium.webdriver.common.by import By

class Locators:
    login_and_register_button = (By.XPATH, ".//button[text()='Вход и регистрация']")
    no_accaunt_button = (By.XPATH, ".//button[text()='Нет аккаунта']")
    email_input = (By.XPATH, ".//input[@name='email']")
    password_input = (By.XPATH, ".//input[@name='password']")
    confirm_password_input = (By.XPATH, ".//input[@name='submitPassword']")
    create_accaunt_button =  (By.XPATH, ".//button[text()='Создать аккаунт']")
    logout_button =  (By.XPATH, ".//button[text()='Выйти']")
    login_button = (By.XPATH, ".//button[text()='Войти']")
    error_text =  (By.XPATH, ".//span[text()='Ошибка']")
    user_name =  (By.XPATH, "//h3[text()='User.']")
    logo =  (By.CLASS_NAME, "svgSmall")
    red_border =  (By.CLASS_NAME,'input_inputError__fLUP9')
    add_announcement = (By.XPATH, ".//button[text()='Разместить объявление']")
    name_input = (By.XPATH, "//input[@name='name']")
    category_input = (By.XPATH, "//input[@name='category']/following-sibling::*[1]")
    city_input = (By.XPATH, "//input[@name='city']/following-sibling::*[1]")
    description_input = (By.XPATH, "//textarea[@name='description']")
    price_input = (By.XPATH, "//input[@name='price']")
    create_button = (By.XPATH, ".//button[text()='Опубликовать']")
    new_product_checkbox = (By.XPATH, "//label[text()='Новый']/preceding-sibling::*[1]")
    old_product_checkbox = (By.XPATH, "//label[text()='Б/У']/preceding-sibling::*[1]")
    profile_button = (By.CLASS_NAME, "circleSmall")
    my_profile_text = (By.XPATH, "//h1[text()='Мой профиль']")
    error_text_add_announcement = (By.XPATH, "//form[@class='popUp_shell__LuyqR']//h1[text()='Чтобы разместить объявление, авторизуйтесь']")
    edit_button = (By.XPATH, "//button[@class='editButton']")
    random_city_text = (By.XPATH, "//span[text()='{}']")
    random_category_text = (By.XPATH, "//span[text()='{}']")
    created_name = (By.XPATH, "//h2[text()='{}']")
    created_random_city_name = (By.XPATH, "//h3[text()='{}']")

